import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Material UI',
  description: 'Generated by create next app',
  head: [
    <link
      key="material-icons-font"
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />,
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include other head elements here */}
        {metadata.head}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
